RGB_MATRIX_ENABLE = yes     # Enable RGB matrix
RGB_MATRIX_DRIVER = WS2812  # Set Driver to WS2812
RGBLIGHT_ENABLE = no

QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
SLEEP_LED_ENABLE = yes
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no

LTO_ENABLE = yes
